apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-claim
  namespace: st
spec:
  storageClassName: local-storage # it is refering for the pv
  resources:
    requests:
      storage: 1Gi # storage size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # mode of read and write for storage
