apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-claim
  namespace: st
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
