apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: st
  labels:
    name: myapp
spec:
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: local-pvc-claim
  containers:
  - name: myapp
    image: "nginx:latest"
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html/
