# we have created a user, now we want to provide access to the user inside the kubernetes

# first lets give only pod access

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: pod-level-access-user-sai
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]

---
# cluster role binding the user to access pods across namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-role-binding
  namespace: default
subjects:
- kind: User
  name: sai
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-level-access-user-sai
  apiGroup: rbac.authorization.k8s.io


